language: cpp
sudo: required
dist: trusty
os: linux
compiler: gcc
matrix:
  include:
  - env: COMPANION_PLATFORM='linux64'
  - env: COMPANION_PLATFORM='windows32'
  - env: COMPANION_PLATFORM='windows64'

install:
  - git submodule update --init --recursive
  - COMPANION_TARGET="${COMPANION_PLATFORM::${#COMPANION_PLATFORM}-2}"
  - ./build/${COMPANION_TARGET}/requirements.sh

before_script:
  - 'if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      . /opt/qt59/bin/qt59-env.sh;
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      echo "give xvfb some time to start";
      sleep 3;
    fi'

script:
  - source ./build/${COMPANION_TARGET}/build.sh
